# You can use this file to create a conda environment like:
#    conda env create -f environment.yml 
name: sarek.pathfindr
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=3.5.1  
  - conda-forge::r-dplyr=0.8.0.1
  - conda-forge::r-ggplot2=3.0.0
  - conda-forge::r-ggrepel=0.8.1 
  - conda-forge::r-kableextra=1.1.0
  - conda-forge::r-tictoc=1.0
  - bioconda::bioconductor-annotationdbi=1.44.0
  - bioconda::bioconductor-delayedarray=0.8.0
  - bioconda::bioconductor-genomicranges=1.34.0
  - bioconda::bioconductor-genomicfeatures=1.34.1
  - bioconda::bioconductor-variantannotation=1.28.3
  - bioconda::r-data.table=1.11.6
  - r-config=0.3 
  - r-dbi=1.1.0
  - r-devtools=1.13.6
  - r-htmltable=1.12
  - r-htmltools=0.3.6
  - r-knitr=1.20
  - r-rmarkdown=1.10
  - r-rcolorbrewer=1.1_2 
  - r-stringr=1.3.1 
  - r-xml2=1.2.0
