default:
  reference:  "GRCh38"
  ascat_directory: "/home/szilva/dev/sarek.pathfindr/pf_test/VariantCalling/Ascat"
  freec_directory: "/home/szilva/dev/sarek.pathfindr/pf_test/VariantCalling/ControlFREEC"
  manta_directory: "/home/szilva/dev/sarek.pathfindr/pf_test/Annotation/SnpEff"
  strelka_directory: "/home/szilva/dev/sarek.pathfindr/pf_test/Annotation/VEP.CADD"
  haplotyper_directory: "/home/szilva/dev/sarek.pathfindr/pf_test/Annotation/VEP.CADD"
  mutect2file: "/home/szilva/dev/sarek.pathfindr/pf_test/Annotation/VEP.CADD/mutect2_P2233_101T_vs_P2233_120N.AF.snpEff.ann.vep.ann.vcf"
  
  # these are the default database files: if your files are at a separate location 
  # (i.e. you have a population-specific SNV or SV table, or your own list of 
  # cancer genes), overwrite these values

  tumorgenes: "~/reports/reference_data/cancer_gene_census.csv"
  local_tumorgenes: "~/reports/reference_data/2018_gene_list_tere_ref.csv"

  hotspots_snv: "~/reports/reference_data/hotspots_v2_snv.csv"
  snptable: "~/reports/reference_data/swegen_snp_counts.small.csv"
  coding_table: "~/reports/reference_data/cosmic_coding_table.csv"
  noncoding_table: "~/reports/reference_data/cosmic_noncoding_table.csv"
  hotspots_inframe: "~/reports/reference_data/hotspots_v2_inframe.csv"
  
  fusions_table: "~/reports/reference_data/cosmic_fusions_table.csv"

  # score thresholds are always calculated as "greater than" (>), so 
  # value 3 will _not_ be presented, only 4,5,...

  default_threshold: 3
  mutect2_threshold: 3
  strelka_threshold: 3
  haplotypecaller_threshold: 3
  manta_threshold: 3
  ascat_threshold: 3
  freec_threshold: 3
